version: "3.9"
services:
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
  order:
    build: ./order 
    depends_on:
      - nats
    links:
      - nats
  customer:
    build: ./customer 
    depends_on:
      - nats
    links:
      - nats
  test:
    build: ./test-app
    entrypoint: "npm test"
    depends_on:
      - nats
      - order
      - customer
    links:
      - nats
      - order
      - customer
volumes:
  logvolume01: {}